security:
    encoders:
        AppBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_CONNECT_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        sensiolabs_connect:
            id: sensiolabs.jobboard.doctrine.repository.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            sensiolabs_connect:
                check_path:  /session/callback
                login_path:  /login
                remember_me: false
                provider:    sensiolabs_connect
            logout:          ~
            anonymous:       true

    access_control:
        - { path: ^/manage, roles: ROLE_USER }
        - { path: ^/backend, roles: ROLE_ADMIN }
